name: frontendTesting
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        uses: jaid/action-npm-install@v1.2.1
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
      
